spring.application.name=TD5

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=meilleur
spring.datasource.driver-class-name=org.postgresql.Driver

sspring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true