spring.application.name=TD5

spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=product_manager_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect